apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gloo.oss-demo.hillghost.com
  namespace: gloo-lb
spec:
  secretName: gloo-demo-cert
  dnsNames:
    - gloo.oss-demo.hillghost.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
