apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'polaris-routes'
  namespace: 'polaris'
  labels:
    app.kubernetes.io/name: polaris
spec:
  routes:
    - matchers:
       - prefix: '/polaris/'
      routeAction:
        single:
          kube:
            ref:
              name: 'polaris-dashboard'
              namespace: polaris
            port: 80
