apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-cleanup-gloo-system
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - delete
  - apiGroups:
      - gateway.solo.io
    resources:
      - '*'
    verbs:
      - list
      - delete