apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-gateway-secret-create-vwc-update-gloo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gloo-gateway-secret-create-vwc-update-gloo-system
subjects:
  - kind: ServiceAccount
    name: certgen
    namespace: gloo-system