apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-mutator-gloo-system
rules:
  - apiGroups:
      - gloo.solo.io
    resources:
      - proxies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete