apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-reader-binding-gloo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gloo-resource-reader-gloo-system
subjects:
  - kind: ServiceAccount
    name: gloo
    namespace: gloo-system