apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: gloo
    gloo: rbac
  name: gloo-graphqlapi-mutator-gloo-system
rules:
  - apiGroups:
      - graphql.gloo.solo.io
    resources:
      - graphqlapis
      - graphqlapis/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create