apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: gloo
    gloo: rbac
  name: settings-user-gloo-system
rules:
  - apiGroups:
      - gloo.solo.io
    resources:
      - settings
    verbs:
      - get
      - list
      - watch