apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-migration-gloo-system
rules:
  - apiGroups:
      - gateway.solo.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list