apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-rollout
  namespace: gloo-system