apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: gloo
  template:
    metadata:
      annotations:
        gloo.solo.io/oss-image-tag: 1.12.36
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      labels:
        gloo: gloo
    spec:
      containers:
        - env:
            - name: ENVOY_SIDECAR
              value: "true"
          image: quay.io/solo-io/gloo-envoy-wrapper:1.12.36
          imagePullPolicy: IfNotPresent
          name: envoy-sidecar
          ports:
            - containerPort: 9977
              name: grpc-xds
              protocol: TCP
            - containerPort: 9976
              name: rest-xds
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            tcpSocket:
              port: 9977
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
          volumeMounts:
            - mountPath: /etc/envoy
              name: envoy-sidecar-config
            - mountPath: /etc/envoy/ssl
              name: gloo-mtls-certs
              readOnly: true
        - env:
            - name: GLOO_MTLS_SDS_ENABLED
              value: "true"
          image: quay.io/solo-io/sds:1.12.36
          imagePullPolicy: IfNotPresent
          name: sds
          ports:
            - containerPort: 9988
              name: validation
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            tcpSocket:
              port: 9988
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
          volumeMounts:
            - mountPath: /etc/envoy/ssl
              name: gloo-mtls-certs
              readOnly: true
        - env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: START_STATS_SERVER
              value: "true"
            - name: VALIDATION_MUST_START
              value: "true"
          image: quay.io/solo-io/gloo:1.12.36
          imagePullPolicy: IfNotPresent
          name: gloo
          ports:
            - containerPort: 9988
              name: grpc-validation
              protocol: TCP
            - containerPort: 9966
              name: grpc-proxydebug
              protocol: TCP
            - containerPort: 9979
              name: wasm-cache
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10101
          volumeMounts:
            - mountPath: /etc/gateway/validation-certs
              name: validation-certs
            - mountPath: /etc/gloo
              name: labels-volume
              readOnly: true
      serviceAccountName: gloo
      volumes:
        - name: gloo-mtls-certs
          secret:
            defaultMode: 420
            secretName: gloo-mtls-certs
        - configMap:
            name: envoy-sidecar-config
          name: envoy-sidecar-config
        - downwardAPI:
            items:
              - fieldRef:
                  fieldPath: metadata.labels
                path: labels
          name: labels-volume
        - name: validation-certs
          secret:
            defaultMode: 420
            secretName: gateway-validation-certs