apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    app: gloo
    gloo: rbac
  name: gloo-resource-cleanup
  namespace: gloo-system
rules:
  - apiGroups:
      - gloo.solo.io
    resources:
      - '*'
    verbs:
      - list
      - delete