apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "10"
  labels:
    app: gloo
    gloo: gateway-certgen
  name: gateway-certgen
  namespace: gloo-system
spec:
  template:
    metadata:
      labels:
        gloo: gateway-certgen
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - args:
            - --secret-name=gateway-validation-certs
            - --svc-name=gloo
            - --validating-webhook-configuration-name=gloo-gateway-validation-webhook-gloo-system
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/solo-io/certgen:1.12.36
          imagePullPolicy: IfNotPresent
          name: certgen
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
      restartPolicy: OnFailure
      serviceAccountName: certgen
  ttlSecondsAfterFinished: 60