apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "5"
  labels:
    app: gloo
    gloo: resource-cleanup
  name: gloo-resource-cleanup
  namespace: gloo-system
spec:
  template:
    metadata:
      labels:
        gloo: resource-cleanup
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              kubectl delete --ignore-not-found validatingwebhookconfigurations.admissionregistration.k8s.io gloo-gateway-validation-webhook-gloo-system || exit $?

              if ! kubectl get crd upstreams.gloo.solo.io; then
                echo "Could not find Upstream CRD. Gloo Edge CRDs may have already been deleted. Skipping cleanup of Gloo Edge resources."
                exit 0
              fi

              kubectl delete --ignore-not-found upstreams.gloo.solo.io -n gloo-system -l app=gloo || exit $?

              # gateways can be in multiple namespaces
              kubectl delete --ignore-not-found gateways.gateway.solo.io -n gloo-system -l app=gloo || exit $?
          image: quay.io/solo-io/kubectl:1.12.36
          imagePullPolicy: IfNotPresent
          name: kubectl
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
      restartPolicy: OnFailure
      serviceAccountName: gloo-resource-cleanup
  ttlSecondsAfterFinished: 60