apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "5"
  labels:
    app: gloo
    gloo: resource-rollout
  name: gloo-resource-rollout
  namespace: gloo-system
spec:
  template:
    metadata:
      labels:
        gloo: resource-rollout
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - "# if validation webhook is enabled, wait for deployment rollout so validation service will be available\nkubectl rollout status deployment -n gloo-system gloo\n# apply Gloo Edge custom resources\nkubectl apply -f - <<EOF || exit $?            \n---\n\napiVersion: gateway.solo.io/v1\nkind: Gateway\nmetadata:\n  name: corp-gw\n  namespace: gloo-system\n  labels:\n    app: gloo\nspec:\n  bindAddress: \"::\"\n  bindPort: 8080\n  httpGateway:\n    virtualServiceSelector:\n      gateway-type: private\n  useProxyProto: false\n  ssl: false\n  proxyNames:\n  - corp-gw\n---\n\napiVersion: gateway.solo.io/v1\nkind: Gateway\nmetadata:\n  name: public-gw-ssl\n  namespace: gloo-system\n  labels:\n    app: gloo\nspec:\n  bindAddress: \"::\"\n  bindPort: 8443\n  httpGateway:\n    options:\n      healthCheck:\n        path: /envoy-hc\n    virtualServiceSelector:\n      gateway-type: public\n  useProxyProto: false\n  ssl: true\n  proxyNames:\n  - public-gw\nEOF\n\n# remove the resource-policy annotations that were added temporarily by the gloo-resource-migration job during upgrade\nkubectl annotate upstreams.gloo.solo.io -n gloo-system -l app=gloo helm.sh/resource-policy- || exit $?\nkubectl annotate gateways.gateway.solo.io -n gloo-system -l app=gloo helm.sh/resource-policy- || exit $?\n"
          image: quay.io/solo-io/kubectl:1.12.36
          imagePullPolicy: IfNotPresent
          name: kubectl
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
      restartPolicy: OnFailure
      serviceAccountName: gloo-resource-rollout
  ttlSecondsAfterFinished: 60