apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: gloo
    gloo: gloo-mtls-certgen-cronjob
  name: gloo-mtls-certgen-cronjob
  namespace: gloo-system
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            gloo: gloo-mtls-certs
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - args:
                - --secret-name=gloo-mtls-certs
                - --svc-name=gloo
                - --force-rotation=true
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: quay.io/solo-io/certgen:1.12.36
              imagePullPolicy: IfNotPresent
              name: certgen
              securityContext:
                runAsNonRoot: true
                runAsUser: 10101
          restartPolicy: OnFailure
          serviceAccountName: certgen
      ttlSecondsAfterFinished: 60
  schedule: 0 0 * * SUN