apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "3"
  labels:
    app: gloo
    gloo: resource-migration
  name: gloo-resource-migration
  namespace: gloo-system
spec:
  template:
    metadata:
      labels:
        gloo: resource-migration
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get crd upstreams.gloo.solo.io; then
                echo "Could not find Upstream CRD. Gloo Edge may not be installed yet. Skipping migration job."
                exit 0
              fi

              # remove existing helm labels/annotations since the custom resources are no longer managed by helm.
              # also add resource-policy to tell helm not to delete the resource during upgrade.
              # select by label app=gloo, which is on all CRs from the gloo helm chart.
              kubectl annotate --overwrite upstreams.gloo.solo.io -n gloo-system -l app=gloo helm.sh/hook- helm.sh/hook-weight- meta.helm.sh/release-name- meta.helm.sh/release-namespace- helm.sh/resource-policy=keep || exit $?
              kubectl label upstreams.gloo.solo.io -n gloo-system -l app=gloo,app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by- || exit $?

              # gateways can be in multiple namespaces
              kubectl annotate --overwrite gateways.gateway.solo.io -n gloo-system -l app=gloo helm.sh/hook- helm.sh/hook-weight- meta.helm.sh/release-name- meta.helm.sh/release-namespace- helm.sh/resource-policy=keep || exit $?
              kubectl label gateways.gateway.solo.io -n gloo-system -l app=gloo,app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by- || exit $?
          image: quay.io/solo-io/kubectl:1.12.36
          imagePullPolicy: IfNotPresent
          name: kubectl
          securityContext:
            runAsNonRoot: true
            runAsUser: 10101
      restartPolicy: OnFailure
      serviceAccountName: gloo-resource-migration
  ttlSecondsAfterFinished: 60