apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
  labels:
    app: gloo
    gloo: rbac
  name: certgen
  namespace: gloo-system