apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gateway-proxy-id: corp-gw
    gloo: gateway-proxy
  name: corp-gw
  namespace: gloo-system
spec:
  ports:
    - name: http
      nodePort: 32080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    gateway-proxy: live
    gateway-proxy-id: corp-gw
  type: NodePort