apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelb-ui
  namespace: yelb
spec:
  maxReplicas: 100
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelb-ui
  targetCPUUtilizationPercentage: 80

