kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: yelb-ui
spec:
  hosts:
    - "yelb.sandbox.hillghost.com"
  pathPrefixes:
    - /
  replicas:
    max: 50
  targetPendingRequests: 10
  scaleTargetRef:
    deployment: yelb-ui
    service: yelb-ui
    port: 80
