kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: yelb-appserver
spec:
  host: "yelb.sandbox.hillghost.com"
  pathPrefixes:
    - /api
  replicas:
    max: 50
  targetPendingRequests: 10
  scaleTargetRef:
    deployment: yelb-appserver
    service: yelb-appserver
    port: 4567
