apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/limit-rps: "5"
  name: yelb-ui
  namespace: keda
spec:
  ingressClassName: nginx-ingress
  rules:
  - host: yelb.sandbox.hillghost.com
    http:
      paths:
      - backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              name: http
        path: /api
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - yelb.sandbox.hillghost.com
    secretName: yelb-ui-tls
