# Source: basic-demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-basic-demo
  labels:
    app.kubernetes.io/name: basic-demo
    helm.sh/chart: basic-demo-0.5.2
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: basic-demo
      app.kubernetes.io/instance: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: basic-demo
        app.kubernetes.io/instance: demo
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: fargle
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: basic-demo
          image: "quay.io/fairwinds/docker-demo:1.2.0"
          imagePullPolicy: Always
          env:
            - name: REFRESH_INTERVAL
              value: "500"
            - name: TITLE
              value: "Kubernetes Demo"
            - name: METADATA
              value: "Andy's Kube Demo for IDP!"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsUser: 1200
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
              memory: 512Mi # TODO: Set this to the amount of Memory you want to reserve for your workload
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
              memory: 512Mi # TODO: Set this to the maximum amount of memory you want your workload to use
  replicas: 3
