apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: yelb-appserver
spec:
  scaleTargetRef:
    name: demo-basic-demo
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.fw-prometheus:9090
      metricName: nginx_ingress_controller_requests
      threshold: '20'
      query: round(sum(rate(nginx_ingress_controller_requests{service="demo-basic-demo"}[1m])))

