# Source: policy-reporter/charts/kyvernoPlugin/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    helm.sh/chart: kyverno-plugin-1.6.2
    app.kubernetes.io/name: kyverno-plugin
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "1.6.1"
    app.kubernetes.io/component: plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: policy-reporter
  name: policy-reporter-kyverno-plugin
rules:
- apiGroups:
  - '*'
  resources:
  - policies
  - policies/status
  - clusterpolicies
  - clusterpolicies/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - policyreports
  - clusterpolicyreports
  verbs:
  - get
  - list

