# Source: policy-reporter/charts/ui/templates/secret-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-reporter-ui-secret-reader
  namespace: policy-reporter
  labels:
    helm.sh/chart: ui-2.10.2
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "1.9.1"
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: policy-reporter
roleRef:
  kind: Role
  name: policy-reporter-ui-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: "ServiceAccount"
  name: policy-reporter-ui
  namespace: policy-reporter

