# Source: policy-reporter/charts/kyvernoPlugin/templates/secret-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policy-reporter-kyverno-plugin-secret-reader
  namespace: policy-reporter
  labels:
    helm.sh/chart: kyverno-plugin-1.6.2
    app.kubernetes.io/name: kyverno-plugin
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "1.6.1"
    app.kubernetes.io/component: plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: policy-reporter
roleRef:
  kind: Role
  name: policy-reporter-kyverno-plugin-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: "ServiceAccount"
  name: policy-reporter-kyverno-plugin
  namespace: policy-reporter

