# Source: policy-reporter/charts/kyvernoPlugin/templates/config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: policy-reporter-kyverno-plugin-config
  namespace: policy-reporter
  labels:
    helm.sh/chart: kyverno-plugin-1.6.2
    app.kubernetes.io/name: kyverno-plugin
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "1.6.1"
    app.kubernetes.io/component: plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: policy-reporter
type: Opaque
data:
  config.yaml: YmxvY2tSZXBvcnRzOgogIGVuYWJsZWQ6IGZhbHNlCiAgZXZlbnROYW1lc3BhY2U6IGRlZmF1bHQKICByZXN1bHRzOgogICAga2VlcE9ubHlMYXRlc3Q6IGZhbHNlCiAgICBtYXhQZXJSZXBvcnQ6IDIwMAoKbGVhZGVyRWxlY3Rpb246CiAgZW5hYmxlZDogZmFsc2UKICByZWxlYXNlT25DYW5jZWw6IHRydWUKICBsZWFzZUR1cmF0aW9uOiAxNQogIHJlbmV3RGVhZGxpbmU6IDEwCiAgcmV0cnlQZXJpb2Q6IDIKCmxvZ2dpbmc6CiAgZW5jb2Rpbmc6IGNvbnNvbGUKICBsb2dMZXZlbDogMAogIGRldmVsb3BtZW50OiBmYWxzZQoKYXBpOgogIGxvZ2dpbmc6IGZhbHNlCiAgYmFzaWNBdXRoOgogICAgdXNlcm5hbWU6IAogICAgcGFzc3dvcmQ6IAogICAgc2VjcmV0UmVmOiAK

