apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: gpu
spec:
  ephemeralStorage:
    iops: 3000
    size: 1000Gi
    throughput: 125
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: eksctl-andy-ai-cluster-AutoModeNodeRole-mfDxggqGnDcQ
  securityGroupSelectorTerms:
  - id: sg-0ec74ce50bb548912
  snatPolicy: Random
  subnetSelectorTerms:
  - id: subnet-01ba9c49692cf1cf9
  - id: subnet-0190b3c01cdc4a5fb
  - id: subnet-054a3712cd2d55c7f
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  template:
    metadata:
      labels:
        cost-area: research
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: gpu
      taints:
        - key: ray.io/node-type
          value: worker
          effect: NoSchedule
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["g"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: In
          values: ["5"]
        - key: "eks.amazonaws.com/instance-gpu-count"
          operator: In
          values: ["2"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  limits:
    cpu: "100"
    memory: 100G
