apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: kubecost-svc-service-monitor
  namespace: kubecost
spec:
  endpoints:
  - interval: 30s
    port: tcp-model
    scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
    - kubecost
  selector:
    matchLabels:
      app: cost-analyzer
