# Source: argo-cd/templates/argocd-notifications/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-notifications-controller
  labels:
    helm.sh/chart: argo-cd-5.51.6
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.9.3"
rules:
  - apiGroups:
    - "argoproj.io"
    resources:
    - "applications"
    verbs:
    - get
    - list
    - watch
    - update
    - patch

