apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v12
  name: vote-bot
spec:
  selector:
    matchLabels:
      app: vote-bot
      version: v12
  template:
    metadata:
      labels:
        app: vote-bot
        version: v12
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc:80
        - name: OC_AGENT_HOST
          value: "default-deployment-collector.opentelemetry-operator-system:55678"
        image: docker.l5d.io/buoyantio/emojivoto-web:v12
        name: vote-bot
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 20m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
