apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: emoji
spec:
  scaleTargetRef:
    name: emoji
  minReplicaCount: 2
  maxReplicaCount: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-operated.fw-prometheus:9090
      metricName: nginx_ingress_controller_requests
      threshold: '600'
      query: round(sum(rate(container_network_receive_bytes_total{namespace="team1", pod=~"emoji-.+"}[2m])))

