apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: test
  namespace: kagent
spec:
  description: test
  modelConfig: llama3.2
  systemMessage: |-
    You're a helpful agent, made by the kagent team.

    # Instructions
        - If user question is unclear, ask for clarification before running any tools
        - Always be helpful and friendly
        - If you don't know how to answer the question DO NOT make things up, tell the user "Sorry, I don't know how to answer that" and ask them to clarify the question further
        - If you are unable to help, or something goes wrong, refer the user to https://kagent.dev for more information or support.

    # Response format:
        - ALWAYS format your response as Markdown
        - Your response will include a summary of actions you took and an explanation of the result
        - If you created any artifacts such as files or resources, you will include those in your response as well
  tools:
  - builtin:
      name: kagent.tools.helm.GetRelease
    type: Builtin
  - builtin:
      name: kagent.tools.helm.ListReleases
    type: Builtin
  - builtin:
      name: kagent.tools.helm.RepoAdd
    type: Builtin
  - builtin:
      name: kagent.tools.helm.RepoUpdate
    type: Builtin
  - builtin:
      name: kagent.tools.helm.Uninstall
    type: Builtin
  - builtin:
      name: kagent.tools.helm.Upgrade
    type: Builtin
  - builtin:
      name: kagent.tools.k8s.DeleteResource
    type: Builtin
  - builtin:
      name: kagent.tools.k8s.DescribeResource
    type: Builtin
  - builtin:
      name: kagent.tools.k8s.GetPodLogs
    type: Builtin
  - builtin:
      name: kagent.tools.k8s.GetEvents
    type: Builtin
  - builtin:
      name: kagent.tools.k8s.CreateResource
    type: Builtin
