apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: mistral-small
  namespace: kagent
spec:
  model: mistral-small
  provider: Ollama
  ollama:
    host: http://ollama-srv-f6fd8c.ollama-apps.svc.cluster.local:11434
  # Required: Specify model capabilities
  modelInfo:
    vision: false
    functionCalling: true
    jsonOutput: true
    family: "unknown"
    structuredOutput: true
    multipleSystemMessages: false
