# Source: kyverno/templates/tests/cleanup-controller-liveness.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kyverno-cleanup-controller-liveness
  namespace: kyverno
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.1.1
    helm.sh/chart: kyverno-3.1.1
    team: security
  annotations:
    helm.sh/hook: test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:1.35
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      command:
        - /bin/sh
        - -c
        - sleep 20 ; wget -O- -S --no-check-certificate https://kyverno-cleanup-controller.kyverno:443/health/liveness

