global:
  podLabels:
    team: infrastructure
configs:
  cm:
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.suderman.us.com
