podLabels:
  team: security

kyvernoPlugin:
  enabled: true

ui:
  enabled: true
  plugins:
    kyverno: true
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: policies.suderman.us.com
      path: /

