podLabels:
  team: security

kyvernoPlugin:
  enabled: true
  podLabels:
    team: security

ui:
  enabled: true
  podLabels:
    team: security
  plugins:
    kyverno: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: policies.suderman.us.com
        paths:
          - path: /
            pathType: Prefix

