---
apiVersion: v1
kind: Secret
metadata:
  name: demos
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/sudermanjr/demos
