---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: policy-reporter
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
  name: policy-reporter
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
spec:
  destination:
    namespace: policy-reporter
    server: https://kubernetes.default.svc
  project: default
  source:
    path: multi-cluster-scale/manifests/policy-reporter
    repoURL: https://github.com/sudermanjr/demos.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true
