- name: pikube-pre
  hosts:
    - pikube_control_plane
    - pikube_worker
  tasks:
    - name: ping
      ansible.builtin.ping:
    - name: Add all sudermanjr authorized keys
      ansible.posix.authorized_key:
        user: asuderma
        state: present
        key: https://github.com/sudermanjr.keys
    - name: Install packages
      become: true
      apt:
        pkg:
          - curl
          - git
          - vim
          - linux-modules-extra-raspi
        update_cache: true
    - name: Update all packages
      become: true
      apt:
        update_cache: true
        upgrade: dist
    - name: Run install script for control plane
      ansible.builtin.script: k3s-install.sh
      when: role == "control_plane"
    - name: get k3s token
      become: true
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: role == "control_plane"
    - name: Get kubeconfig
      become: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: kubeconfig.yaml
        flat: true
      when: role == "control_plane"
    - name: Install worker nodes
      ansible.builtin.script: |
        K3S_SERVER=https://pikube-0:6443 K3S_TOKEN={{ k3s_token}} k3s-install.sh
      when: role == "worker"
