apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  namespace: kube-system
spec:
  ingressClassName: traefik
  rules:
  - host: traefik.suderman.us.com
    http:
      paths:
      - backend:
          service:
            name: traefik
            port:
              number: 80
        path: /
        pathType: Prefix
