# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-checkoutservice
  labels:
    helm.sh/chart: opentelemetry-demo-0.23.0
    
    opentelemetry.io/name: otel-demo-checkoutservice
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/component: checkoutservice
    app.kubernetes.io/name: otel-demo-checkoutservice
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      
      opentelemetry.io/name: otel-demo-checkoutservice
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: otel-demo-checkoutservice
        app.kubernetes.io/instance: otel-demo
        app.kubernetes.io/component: checkoutservice
        app.kubernetes.io/name: otel-demo-checkoutservice
    spec:
      serviceAccountName: otel-demo
      containers:
        - name: checkoutservice
          image: 'ghcr.io/open-telemetry/demo:1.4.0-checkoutservice'
          imagePullPolicy: Always
          ports:
          
          - containerPort: 8080
            name: service
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: OTEL_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: OTEL_K8S_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OTEL_K8S_POD_UID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
          - name: OTEL_COLLECTOR_NAME
            value: 'otel-demo-otelcol'
          - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
            value: cumulative
          - name: CHECKOUT_SERVICE_PORT
            value: "8080"
          - name: CART_SERVICE_ADDR
            value: 'otel-demo-cartservice:8080'
          - name: CURRENCY_SERVICE_ADDR
            value: 'otel-demo-currencyservice:8080'
          - name: EMAIL_SERVICE_ADDR
            value: http://otel-demo-emailservice:8080
          - name: PAYMENT_SERVICE_ADDR
            value: 'otel-demo-paymentservice:8080'
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: 'otel-demo-productcatalogservice:8080'
          - name: SHIPPING_SERVICE_ADDR
            value: 'otel-demo-shippingservice:8080'
          - name: KAFKA_SERVICE_ADDR
            value: 'otel-demo-kafka:9092'
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(OTEL_COLLECTOR_NAME):4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.instance.id=$(OTEL_K8S_POD_UID),service.namespace=opentelemetry-demo,k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_K8S_POD_NAME)
          resources:
            limits:
              memory: 20Mi
      initContainers:
        - command:
          - sh
          - -c
          - until nc -z -v -w30 otel-demo-kafka 9092; do echo waiting
            for kafka; sleep 2; done;
          image: busybox:latest
          name: wait-for-kafka

