# Source: opentelemetry-demo/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-demo-grafana
  namespace: otel-demo
  labels:
    helm.sh/chart: grafana-6.58.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/version: "10.0.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-demo-grafana
subjects:
- kind: ServiceAccount
  name: otel-demo-grafana
  namespace: otel-demo

