# Source: opentelemetry-demo/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: otel-demo-grafana
  namespace: otel-demo
  labels:
    helm.sh/chart: grafana-6.58.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/version: "10.0.3"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4="
  ldap-toml: ""

