# Source: opentelemetry-demo/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-grafana
  namespace: otel-demo
  labels:
    helm.sh/chart: grafana-6.58.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/version: "10.0.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: otel-demo

