# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-ffspostgres
  labels:
    helm.sh/chart: opentelemetry-demo-0.23.0
    
    opentelemetry.io/name: otel-demo-ffspostgres
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/component: ffspostgres
    app.kubernetes.io/name: otel-demo-ffspostgres
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
  selector:
    
    opentelemetry.io/name: otel-demo-ffspostgres

