---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: demo
    #pod-security.kubernetes.io/enforce: baseline
    #pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/enforce: restricted
  name: demo
spec:
  finalizers:
  - kubernetes
