apiVersion: v1
items:
  - apiVersion: elbv2.k8s.aws/v1beta1
    kind: IngressClassParams
    metadata:
      labels:
        app.kubernetes.io/instance: aws-load-balancer-controller
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: aws-load-balancer-controller
        app.kubernetes.io/version: v2.4.4
        helm.sh/chart: aws-load-balancer-controller-1.4.5
      name: alb
  - apiVersion: networking.k8s.io/v1
    kind: IngressClass
    metadata:
      labels:
        app.kubernetes.io/instance: aws-load-balancer-controller
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: aws-load-balancer-controller
        app.kubernetes.io/version: v2.4.4
        helm.sh/chart: aws-load-balancer-controller-1.4.5
      name: alb
    spec:
      controller: ingress.k8s.aws/alb
kind: List
metadata:
  name: ingress-class