apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: temporal
  name: temporal-db
spec:
  postgres:
    version: '16'
    extensions:
      - name: btree_gin
  instances: 1
  pods:
    persistentVolume:
      size: '10Gi'
